### ISSUE TITLE
flutter_map version 3.0.0

### ISSUE THREAD

**Issue by Pepslee** [rorystephenson/flutter_map_supercluster#1]
There are https://pub.dev/packages/flutter_map/versions/3.0.0-beta.3 new version of flutter_map.
Is plugin support planned for this version of map ?

**Comment by rorystephenson** [comment]
Hi @Pepslee . I will certainly support v3 but I am hesitant on making the necessary changes until a stable v3 is published.

**Comment by Pepslee** [comment]
Hi @rorystephenson.
Stable flutter_map v3 was published a few days ago.
There some interesting [ cluster plugin ](https://github.com/lpongetti/flutter_map_marker_cluster) which flutter_map devs recommend to use, but it very slow compared to yours.  But it has some useful UI features, like spiderfy, clustering animation and some others. If you plan to further develop the plugin  would be great to add something like that, maybe directly borrow )) from [ cluster plugin ](https://github.com/lpongetti/flutter_map_marker_cluster).
https://user-images.githubusercontent.com/13853798/188938145-c709d20d-2e13-41ca-afff-a15ea95a7fbb.mp4

**Comment by rorystephenson** [comment]
> Hi @rorystephenson. Stable flutter_map v3 was published a few days ago. There some interesting [ cluster plugin ](https://github.com/lpongetti/flutter_map_marker_cluster) which flutter_map devs recommend to use, but it very slow compared to yours. But it has some useful UI features, like spiderfy, clustering animation and some others. If you plan to further develop the plugin would be great to add something like that, maybe directly borrow )) from [ cluster plugin ](https://github.com/lpongetti/flutter_map_marker_cluster). https://user-images.githubusercontent.com/13853798/188938145-c709d20d-2e13-41ca-afff-a15ea95a7fbb.mp4

I agree those would be nice features! Right now I'm not actively using this package in production so I'm unlikely to add them soon but I'm open to PRs for sure.

I will get to the v3 update soon hopefully, just out of hospital from a minor surgery so I'm recovering from that.

**Comment by rorystephenson** [comment]
@Pepslee I've renamed this package to `flutter_map_supercluster` and make some big changes/updates. It now requires flutter_map v3.0, it supports adding/removing markers and some other small changes.

I would like to eventually work on the other features you suggested but no guarantees.
