### ISSUE TITLE
Rotate

### ISSUE THREAD

**Issue by morfair** [rorystephenson/flutter_map_supercluster#11]
How to rotate cluster marker and it's child initialMarkers?

**Comment by rorystephenson** [comment]
Hi @morfair . Do you mean you would like the cluster markers to rotate when the map rotates? I am not sure what you mean by rotating the initialMarkers.

**Comment by morfair** [comment]
> Hi @morfair . Do you mean you would like the cluster markers to rotate when the map rotates? I am not sure what you mean by rotating the initialMarkers.

yes! I want rotate map on geolocator heading and rotate markers with cluster markers too

**Comment by rorystephenson** [comment]
@morfair Have you tried the example app? Markers can already rotate, clusters will move when the map is rotated but they stay facing up. I could consider allowing cluster rotation to be configurable but I want to be clear that's actually what you are after.

It would make things easier for me if you could share your code or a video demonstrating the issue.
