### ISSUE TITLE
Marker looses PopUp-Style when splayed clusters are collapsed

### ISSUE THREAD

**Issue by tobesucht** [rorystephenson/flutter_map_supercluster#20]
Hi,

thanks a lot for your work here - your project is really amazing and helpful.

During the customization inside of my project I realized that the PopUp-style of a Marker is removed as soon as the splayed clusters will be collapsed (by zooming out or manually collapsing them). In my case it would be great if the style could be maintained so that the user can find the selected Marker again. Is there a chance to avoid collapsing when a Marker is in PopUp-mode or maintain it´s style even if it is collapsed? I have investigated your code but didn´t found an easy way to manipulate it. Maybe I am overseeing something?

BTW, I am using the mutable SuperClusterLayer. 

Cheers

**Comment by rorystephenson** [comment]
Hi @tobesucht . Thank you for the kind words 🙂.

Do you think you could provide a minimal example so I can see how you are applying the styling and why it is getting removed?

**Comment by tobesucht** [comment]
Hi @rorystephenson, thanks for your swift reply! Of course, here is what I am doing with the styling:
```
SuperclusterLayer.mutable(
                initialMarkers: storyMarkers,  
                indexBuilder: IndexBuilders.rootIsolate,  
                controller: _superclusterController,  
                clusterWidgetSize: const Size(40, 40),  
                anchor: AnchorPos.align(AnchorAlign.center),   
                popupOptions: PopupOptions(  
                  selectedMarkerBuilder: (context, marker) {  
                    return StoryMarker(story: selectedStory!).getIcon(true);  
                  },  
                ),  
                calculateAggregatedClusterData: true,  
                builder: (context, position, markerCount, extraClusterData) {  
                  return Container(  
                    decoration: BoxDecoration(  
                      borderRadius: BorderRadius.circular(20.0),  
                      color: Colors.green,  
                    ),  
                    child: Center(  
                       child: Text(  
                        markerCount.toString(),  
                        style: const TextStyle(color: Colors.white),  
                      ),  
                    ),  
                  );  
                },  
            ),  
```

The StoryMarker.getIcon(true); returns a red Marker if the parameter is true and a green Marker if the parameter is false:

The markers are added only once during build of the widget:
```
for (var x = 0; x < mystories.length; x++) {  
        storyMarkers.add(StoryMarker(story: mystories[x]).asMarker(false));  
      }  
      _superclusterController.replaceAll(storyMarkers);
```

Here is the style definition of the markers:
```
class StoryMarker {  
  final StoryEntity story;  
  
  StoryMarker({required this.story});  
  
  Marker asMarker(bool highlight) => Marker(  
        builder: (context) => getIcon(highlight),  
        rotate: true,  
        rotateAlignment: AnchorAlign.top.rotationAlignment,  
        point:  
            LatLng(double.parse(story.longitude), double.parse(story.latitude)),  
        key: ValueKey(story.storyId),  
      );  
  
  int _getColor(bool highlight) {  
    return ((highlight == true) ? Colors.red : Colors.green).value;  
  }  
  
  Icon getIcon(bool highlight) {  
    return Icon(  
      Icons.spatial_tracking_outlined,  
      color: Color(_getColor(highlight)),  
      size: 40,  
    );  
  }  
}  
```


When the Markers collapse all Markers are turning green. When they are getting uncollapsed they stay green as well.

**Comment by tobesucht** [comment]
I have figured out a workaround which ensures that the selected marker has still the PopUp-style, even if it got clustered (which seems to trigger a HidePopupsOnlyForControllerEvent in project flutter_map_marker_popup, which cannot be avoided). 

I want to share my solution here which works well in my application where only one selected marker is allowed at the same time:

```
@override
  void initState() {
    super.initState();

    PopupState popupState = PopupState.of(context, listen: false);
    popupState.addListener(() {
      // check if I have a selected POI in my internal list
      if (widget.mapManager.storyManager.getSelectedStory() != null &&
          popupState.selectedMarkers.length == 0) {
        // identifies the marker from the marker´s list
        Marker findSelectedMarker =
            widget.mapManager.findSelectedMarker(popupState);
         // re-apply the popup style for the marker
        widget.popupController.showPopupsAlsoFor([findSelectedMarker]);
      }
    });
  }
```
