### ISSUE TITLE
How to change/customise the 'Building clusters' dialog?

### ISSUE THREAD

**Issue by Richard-Walter** [rorystephenson/flutter_map_supercluster#4]
As the title says, is it possible to change/style the dialog that pops up when the clusters are building?
![clustering2](https://user-images.githubusercontent.com/47770368/220468994-81905d3d-a44b-4bbc-937b-6e35c58fe64f.jpg)

**Comment by rorystephenson** [comment]
Hi @Richard-Walter. Please have a look at the documentation of `SuperclusterLayer`. Both this and #5 are achievable with well documented named parameters. In this case see `loadingOverlayBuilder`.
