### ISSUE TITLE
Can we customise the clustering icons?

### ISSUE THREAD

**Issue by Richard-Walter** [rorystephenson/flutter_map_supercluster#5]
As the title says, can we customise the clustering icon?  Even better would be to change the icon depending on the number of items in the cluster, as shown in this example:

![Screenshot 2023-02-22 090754](https://user-images.githubusercontent.com/47770368/220469658-eadd07cb-4d16-46d0-b3b0-4431c9a73fd3.jpg)

**Comment by gidrokolbaska** [comment]
the builder gives you the marker count parameter which you can utilize for icon switching, no?

**Comment by rorystephenson** [comment]
Yep as @gidrokolbaska mentioned you can make the cluster icon whatever you like using the builder and customise the appearance with the provided marker count.
