### ISSUE TITLE
Can't use along flutter_map ^4.0.0

### ISSUE THREAD

**Issue by Richard-Walter** [rorystephenson/flutter_map_supercluster#7]
Hey mate, thanks for this package and your popup package!  Im trying to upgrade to flutter map 4.0.0 along with your popup package 4.1.0 but im getting an issue with this package now:

Running "flutter pub get" in fsd_desktop...
Resolving dependencies...
Because flutter_map_supercluster >=2.2.1 depends on flutter_map ^3.1.0 and fsd_desktop depends on flutter_map ^4.0.0, flutter_map_supercluster >=2.2.1 is forbidden.
So, because fsd_desktop depends on flutter_map_supercluster ^2.3.0, version solving failed.

**Comment by rorystephenson** [comment]
You're very welcome @Richard-Walter 🙂. I've just release 3.0.0 which supports flutter_map 4.0.0.
